apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - image: wilmak2021/msvc_cursos:latest
        name: cursos
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: port
                name: msvc-cursos
            #value: "8002"
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: db_host
                name: msvc-cursos
            #value: "mysql8:3306"
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                key: db_database
                name: msvc-cursos
            #value: msvc_cursos
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                key: db_username
                name: msvc-cursos
            #value: root
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: db_password
                name: msvc-cursos
            #value: root
          - name: USUARIOS_URL
            valueFrom:
              configMapKeyRef:
                key: usuarios_url
                name: msvc-cursos
            #value: msvc-usuarios:8001