apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - image: wilmak2021/msvc_cursos:latest
        name: cursos
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            value: "8002"
          - name: DB_HOST
            value: "mysql8:3306"
          - name: DB_DATABASE
            value: msvc-cursos
          - name: DB_USERNAME
            value: root
          - name: DB_PASSWORD
            value: root
          - name: USUARIOS_URL
            value: msvc-usuarios:8001

