apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgres14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: msvc-usuarios
              #value:  postgres
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: db_database
                  name: msvc-usuarios
              #value: msvc_usuarios
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-postgres
      volumes:
        - name: data-postgres
          #hostPath:
          #  path: /var/lib/postgresql
          #  type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: postgres-persistent-volume-claim