apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql8
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
        - image: mysql:8
          name: mysql8
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: msvc-cursos
              #value: root
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db_database
                  name: msvc-cursos
              #value: msvc_cursos
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data-mysql
      volumes:
        - name: data-mysql
          #hostPath:
            #path: /var/lib/mysql
            #type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: mysql-persistent-volume-claim