apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgres14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value:  postgres
            - name: POSTGRES_DB
              value: msvc_usuarios
