apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-usuarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-usuarios
  template:
    metadata:
      labels:
        app: msvc-usuarios
    spec:
      containers:
        - name: usuarios
          image: wilmak2021/msvc_usuarios:latest
          ports:
            - containerPort: 8001
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: msvc-usuarios
              #value: "8001"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: msvc-usuarios
              #value: "postgres14:5432"
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: db_database
                  name: msvc-usuarios
              #value: msvc_usuarios
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: db_username
                  name: msvc-usuarios
              #value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db_password
                  name: msvc-usuarios
              #value: postgres
            - name: CURSOS_URL
              valueFrom:
                configMapKeyRef:
                  key: cursos_url
                  name: msvc-usuarios
              #value: msvc-cursos:8002