apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql
    type: DirectoryOrCreate